python -u run.py \
  --is_training 1 \
  --root_path ./dataset/m4_daily/ \
  --data_path daily_softs_ready.csv \
  --model_id M4_96_48 \
  --model SOFTS \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --enc_in 1000 \
  --dec_in 1000 \
  --c_out 1000 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 512 \
  --d_ff 512 \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 30 \
  --patience 3 \
  --use_norm 1 \
  --itr 1